fixed some extra stuff that was missed
ToniMacaroni/ComputerInterface pull request #67
Opened 2022-08-09 02:41 UTC by developer9998

so, what did i do?

fixed the name tab sometimes displaying a wrong name
before
![image](https://user-images.githubusercontent.com/81720436/183551457-b343a9c2-a78c-4fc1-8727-18eaa7b54f43.png)
after
![image](https://user-images.githubusercontent.com/81720436/183551505-91cf71a7-0cc8-4f68-b76a-8782484269a9.png)

fixed your colour not changing if you weren't in a room
before
https://user-images.githubusercontent.com/81720436/183551593-2ec95f0f-3821-4aef-b555-ad3c3cd06c27.mp4
after
https://user-images.githubusercontent.com/81720436/183551605-efe47455-0434-40f2-9f0b-a3fda5bab8fc.mp4

updated the credits tab                                  
couldn't get any screenshots/videos, sorry!

2022-08-31 03:01 UTC, Graicc requested changes

2022-08-31 03:01 UTC, Graicc commented on ComputerInterface/Views/GameSettings/JoinRoomView.cs
> +=======
You didn't finish the merge

2022-08-31 03:01 UTC, Graicc commented on ComputerInterface/Views/GameSettings/JoinRoomViewCallbacks.cs
> +=======
Same here

2022-08-31 03:01 UTC, Graicc commented on ComputerInterface/Views/GameSettings/JoinRoomViewCallbacks.cs
> +        // public override void OnSchoolFailed(short returnCode, string message) => view.Redraw();
OnSchoolFailed?

2022-08-31 03:01 UTC, Graicc commented on ComputerInterface/Views/GameSettings/CreditsView.cs
> +				.AppendLine("Sound design by David Anderson Kirk");
Is this not already covered in the pages above?

2022-09-23 18:46 UTC, developer9998 commented on ComputerInterface/Views/GameSettings/JoinRoomViewCallbacks.cs
> +        // public override void OnSchoolFailed(short returnCode, string message) => view.Redraw();
i didnt mess with that lol

2022-09-23 18:48 UTC, developer9998 commented on ComputerInterface/Views/GameSettings/JoinRoomView.cs
> +=======
what now i hardly know anything about github

2022-09-23 18:49 UTC, developer9998 commented on ComputerInterface/Views/GameSettings/CreditsView.cs
> +				.AppendLine("Sound design by David Anderson Kirk");
github being stupid

2022-09-23 19:16 UTC, closed without merging