minor tweak
ToniMacaroni/ComputerInterface pull request #72
Opened 2022-09-23 19:21 UTC by developer9998

-updated credits tab
-possibly fixed names and colours not changing for others

hopefully i didnt fuck this up

2022-10-25 16:01 UTC, Graicc requested changes

2022-10-25 16:01 UTC, Graicc commented on ComputerInterface/BaseGameInterface.cs
> +                GorillaTagger.Instance.myVRRig.photonView.RPC("InitializeNoobMaterial", RpcTarget.All, color.r, color.g, color.b, GorillaComputer.instance == null || GorillaComputer.instance.leftHand
```suggestion
                GorillaTagger.Instance.myVRRig.photonView.RPC("InitializeNoobMaterial", RpcTarget.All, color.r, color.g, color.b, GorillaComputer.instance?.leftHanded ?? true);
```

2022-10-25 16:01 UTC, Graicc commented on ComputerInterface/Views/GameSettings/NameSettingView.cs
> +
This just leads to people trying things until they manage to circumvent the name filter. In a perfect world, CI would also ban on bad names, but I don't want to risk false bans. 
```suggestion
```

2022-10-25 16:01 UTC, Graicc commented on ComputerInterface/Views/GameSettings/NameSettingView.cs
> +
CI really should just cap the name length to prevent people from sending excess data, which could potentially cause issues with the anti-cheat

```suggestion
```

2022-10-25 16:01 UTC, Graicc commented on ComputerInterface/Views/GameSettings/ColorSettingView.cs
> +            str.BeginColor("ffffff").Repeat("=", SCREEN_WIDTH).EndColor().AppendLine();
Assuming you made this change because `_color` was causing null exceptions? This suggestion would fix it if that's the case.
```suggestion
            str.BeginColor(_color ?? Color.white).Repeat("=", SCREEN_WIDTH).EndColor().AppendLine();
```

2022-10-25 16:01 UTC, Graicc commented on ComputerInterface/Views/GameSettings/ColorSettingView.cs
> +            str.BeginColor("ffffff").Repeat("=", SCREEN_WIDTH).EndColor().AppendLines(2);
See above

```suggestion
            str.BeginColor(_color ?? Color.white).Repeat("=", SCREEN_WIDTH).EndColor().AppendLines(2);
```

2022-10-25 16:01 UTC, Graicc commented on ComputerInterface/BaseGameInterface.cs
> +                return GorillaComputer.instance.savedName;
```suggestion
            return !GorillaComputer.instance.savedName.IsNullOrWhiteSpace() ? GorillaComputer.instance.savedName : GorillaComputer.instance.savedName;
```

2022-10-28 20:04 UTC, developer9998 commented on ComputerInterface/Views/GameSettings/NameSettingView.cs
> +
didn't think about that

2022-10-28 20:05 UTC, developer9998 commented on ComputerInterface/Views/GameSettings/NameSettingView.cs
> +
from what ive heard people are getting banned from entering long roomnames with CI but thats unrelated

2022-10-28 20:06 UTC, developer9998 commented on ComputerInterface/Views/GameSettings/ColorSettingView.cs
> +            str.BeginColor("ffffff").Repeat("=", SCREEN_WIDTH).EndColor().AppendLine();
not sure if i missed an update but the colour view i built with the source code and the colour view in the release looked different so i must've rushed to finish it or whatever

2022-10-29 17:13 UTC, closed without merging